/**
 * tools/codegen.cpp — MCFlow code generator (Phase 6)
 *
 * Usage:  ./codegen <deployment_plan.json>
 *
 * Reads the deployment plan and emits two files into generated/:
 *   generated/main_generated.cpp   — compilable C++ scaffold
 *   generated/Makefile             — with targets: all, run, clean
 *
 * Ring buffer sizing (paper Section IV):
 *   N = max(2, ceil(deadline_downstream / period_upstream) + pipeline_depth)
 *
 * A static_assert(N >= pipeline_depth) is emitted per buffer; if a
 * misconfigured plan would produce N < pipeline_depth the build fails
 * at compile time.
 */

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <map>
#include <algorithm>
#include <stdexcept>
#include <cstdlib>
#include "../include/nlohmann/json.hpp"
#include "../dag.hpp"
#include "../ring_buffer.hpp"

using json = nlohmann::json;

// ---------------------------------------------------------------------------
//  In-memory model
// ---------------------------------------------------------------------------

struct SubtaskGen {
    int         id;
    std::string component_type;
    int         core;
    int         priority;
    uint64_t    period_ns;
    uint64_t    deadline_ns;
    std::string output_type;
};

struct ConnectionGen {
    int upstream;
    int downstream;
};

// ---------------------------------------------------------------------------
//  Deployment plan parsing
// ---------------------------------------------------------------------------

static void parse_plan(const std::string& path,
                        std::vector<SubtaskGen>&    subtasks,
                        std::vector<ConnectionGen>& conns)
{
    std::ifstream f(path);
    if (!f) throw std::runtime_error("cannot open: " + path);
    json j = json::parse(f);

    for (const auto& task : j.at("tasks")) {
        for (const auto& st : task.at("subtasks")) {
            SubtaskGen s;
            s.id             = st.at("id").get<int>();
            s.component_type = st.at("component_type").get<std::string>();
            s.core           = st.at("core").get<int>();
            s.priority       = st.at("priority").get<int>();
            s.period_ns      = st.value("period_ns",   uint64_t{0});
            s.deadline_ns    = st.value("deadline_ns", uint64_t{0});
            s.output_type    = st.value("output_type", std::string{"double"});
            subtasks.push_back(s);
        }
    }

    for (const auto& c : j.at("connections")) {
        ConnectionGen cg;
        cg.upstream   = c.at("upstream").get<int>();
        cg.downstream = c.at("downstream").get<int>();
        conns.push_back(cg);
    }
}

// ---------------------------------------------------------------------------
//  Code generation
// ---------------------------------------------------------------------------

static void generate_cpp(
    const std::string&              out_path,
    const std::string&              plan_path,
    const std::vector<SubtaskGen>&  subtasks,
    const std::vector<ConnectionGen>& conns,
    const std::vector<int>&         order,
    const DAG&                      dag,
    int                             depth)
{
    std::map<int, const SubtaskGen*> sub;
    for (const auto& s : subtasks) sub[s.id] = &s;

    // Build id → DAG::Node* for O(1) lookup inside generate loops
    std::map<int, const DAG::Node*> node_map;
    for (const auto& n : dag.nodes()) node_map[n.id] = &n;

    std::ofstream f(out_path);
    if (!f) throw std::runtime_error("cannot create: " + out_path);

    // ── header ──────────────────────────────────────────────────────────────
    f << "// AUTO-GENERATED by tools/codegen — DO NOT EDIT\n"
      << "// Source: " << plan_path << "\n"
      << "// pipeline_depth = " << depth << "\n"
      << "// Regenerate: ./codegen " << plan_path << "\n\n"
      << "#include <iostream>\n"
      << "#include <atomic>\n"
      << "#include <chrono>\n"
      << "#include <thread>\n"
      << "#include \"../team_manager.hpp\"\n"
      << "#include \"../ring_buffer.hpp\"\n\n";

    // ── ring buffer declarations ─────────────────────────────────────────────
    f << "// ============================================================\n"
      << "// Ring buffers\n"
      << "// N = max(2, ceil(D_downstream / T_upstream) + pipeline_depth)\n"
      << "// pipeline_depth = " << depth << "\n"
      << "// ============================================================\n\n";

    for (const auto& c : conns) {
        const auto* up   = sub.at(c.upstream);
        const auto* down = sub.at(c.downstream);
        std::size_t n    = ring_buffer_n(up->period_ns, down->deadline_ns, depth);
        std::size_t jif  = (up->period_ns == 0) ? 0
            : (down->deadline_ns + up->period_ns - 1) / up->period_ns;
        std::string dtype = (up->output_type == "void" || up->output_type.empty())
                            ? "double" : up->output_type;

        f << "// edge " << c.upstream << "→" << c.downstream
          << ": T=" << up->period_ns/1000000 << "ms"
          << " D=" << down->deadline_ns/1000000 << "ms"
          << " ceil(D/T)=" << jif << " depth=" << depth << " N=" << n << "\n";
        f << "static RingBuffer<" << dtype << ", " << n << "> "
          << "ring_" << c.upstream << "_" << c.downstream << ";\n";
        f << "static_assert(" << n << " >= " << depth << ",\n"
          << "    \"ring_" << c.upstream << "_" << c.downstream
          << ": N must be >= pipeline_depth=" << depth << "\");\n";
        f << "static std::size_t seq_" << c.upstream << "_" << c.downstream << " = 0;\n\n";
    }

    // ── shared output atomics ────────────────────────────────────────────────
    f << "// ============================================================\n"
      << "// Shared output state (one atomic per non-void output)\n"
      << "// ============================================================\n\n";
    for (const auto& s : subtasks) {
        if (s.output_type != "void" && !s.output_type.empty())
            f << "static std::atomic<" << s.output_type << "> out_" << s.id << "{0};\n";
    }
    f << "\n";

    // ── execute stubs ────────────────────────────────────────────────────────
    f << "// ============================================================\n"
      << "// Execute functions — fill in component logic\n"
      << "// ============================================================\n\n";

    for (int id : order) {
        const auto* s          = sub.at(id);
        const auto* node       = node_map.at(id);
        bool        is_source  = node->predecessors.empty();
        bool        has_output = (s->output_type != "void" && !s->output_type.empty());
        bool        has_succ   = !node->successors.empty();

        f << "static void execute_" << id << "() {\n"
          << "    // [subtask " << id << " / " << s->component_type << "]"
          << "  core=" << s->core << "  prio=" << s->priority
          << "  T=" << s->period_ns/1000000 << "ms"
          << "  D=" << s->deadline_ns/1000000 << "ms\n";

        // read from upstream ring buffers
        if (!is_source) {
            for (int up_id : node->predecessors) {
                f << "    auto in_from_" << up_id << " = ring_" << up_id << "_" << id
                  << ".read(seq_" << up_id << "_" << id << ");\n"
                  << "    (void)in_from_" << up_id << "; // TODO: use upstream value\n";
            }
        }

        f << "    // TODO: implement subtask_" << id << " (" << s->component_type << ") logic\n";
        if (has_output) {
            f << "    " << s->output_type << " result{0}; // replace with real computation\n"
              << "    out_" << id << ".store(result);\n";
        }

        // write to downstream ring buffers
        if (has_succ) {
            for (int dn_id : node->successors) {
                if (!has_output) continue;
                f << "    ring_" << id << "_" << dn_id
                  << ".write(seq_" << id << "_" << dn_id << ", out_" << id << ".load());\n"
                  << "    ring_" << id << "_" << dn_id
                  << ".release(seq_" << id << "_" << dn_id << ");\n"
                  << "    seq_" << id << "_" << dn_id << "++;\n";
            }
        }

        // release upstream slots
        if (!is_source) {
            for (int up_id : node->predecessors) {
                f << "    ring_" << up_id << "_" << id
                  << ".release(seq_" << up_id << "_" << id << ");\n";
            }
        }

        f << "}\n\n";
    }

    // ── DAG builder ──────────────────────────────────────────────────────────
    f << "// ============================================================\n"
      << "// DAG topology\n"
      << "// ============================================================\n\n"
      << "static void build_dag(DAG& dag) {\n";
    for (const auto& s : subtasks)
        f << "    dag.add_node(" << s.id << ", nullptr); // subtask " << s.id << " (" << s.component_type << ")\n";
    for (const auto& c : conns)
        f << "    dag.add_edge(" << c.upstream << ", " << c.downstream << ");\n";
    f << "}\n\n";

    // ── SubtaskInfo helper ───────────────────────────────────────────────────
    f << "static SubtaskInfo make_info(int id, const char* type, int core, int prio,\n"
      << "                             uint64_t period_ns, uint64_t deadline_ns) {\n"
      << "    SubtaskInfo info;\n"
      << "    info.id             = id;\n"
      << "    info.component_type = type;\n"
      << "    info.core           = core;\n"
      << "    info.priority       = prio;\n"
      << "    info.period_ns      = period_ns;\n"
      << "    info.deadline_ns    = deadline_ns;\n"
      << "    return info;\n"
      << "}\n\n";

    // ── main ────────────────────────────────────────────────────────────────
    f << "// ============================================================\n"
      << "// main\n"
      << "// ============================================================\n\n"
      << "int main() {\n";

    for (const auto& s : subtasks)
        f << "    Subtask s" << s.id << "(" << s.id << ", execute_" << s.id << ");\n";

    f << "\n    DAG dag;\n"
      << "    build_dag(dag);\n\n"
      << "    TeamManager tm;\n"
      << "    tm.initialize({\n";
    for (const auto& s : subtasks) {
        f << "        {make_info(" << s.id
          << ", \"" << s.component_type << "\""
          << ", " << s.core
          << ", " << s.priority
          << ", " << s.period_ns << "ULL"
          << ", " << s.deadline_ns << "ULL"
          << "), &s" << s.id << "},\n";
    }
    f << "    }, dag);\n\n";

    // Print ring buffer sizes at runtime
    f << "    std::cout << \"Ring buffer sizes (N = max(2, ceil(D/T) + depth="
      << depth << ")):\\n\";\n";
    for (const auto& c : conns) {
        const auto* up   = sub.at(c.upstream);
        const auto* down = sub.at(c.downstream);
        std::size_t n    = ring_buffer_n(up->period_ns, down->deadline_ns, depth);
        f << "    std::cout << \"  " << c.upstream << "→" << c.downstream
          << ": N=" << n << "\\n\";\n";
    }
    f << "    // Runtime verification (matches compile-time values above)\n";
    for (const auto& c : conns) {
        f << "    std::cout << \"  " << c.upstream << "→" << c.downstream
          << " (runtime): \" << tm.ring_buffer_size(" << c.upstream << ", " << c.downstream
          << ") << \"\\n\";\n";
    }
    f << "\n    tm.start();\n\n";

    // Identify source subtasks from DAG (no predecessors)
    std::vector<int> sources;
    for (const auto& n : dag.nodes())
        if (n.predecessors.empty())
            sources.push_back(n.id);

    // Use the shortest source period as fire interval
    uint64_t fire_ns = 200'000'000ULL;
    for (int src_id : sources) {
        uint64_t p = sub.at(src_id)->period_ns;
        if (p > 0 && p < fire_ns) fire_ns = p;
    }
    uint64_t fire_ms = std::max(uint64_t{1}, fire_ns / 1'000'000);

    f << "    constexpr int NUM_JOBS = 5;\n"
      << "    for (int job = 0; job < NUM_JOBS; job++) {\n"
      << "        std::this_thread::sleep_for(std::chrono::milliseconds(" << fire_ms << "));\n";
    for (int src_id : sources)
        f << "        tm.notify(" << src_id << ");\n";
    f << "    }\n\n"
      << "    std::this_thread::sleep_for(std::chrono::milliseconds(" << (fire_ms * 3) << "));\n"
      << "    tm.stop();\n"
      << "    return 0;\n"
      << "}\n";
}

static void generate_makefile(const std::string& out_path) {
    std::ofstream f(out_path);
    if (!f) throw std::runtime_error("cannot create: " + out_path);
    f << "CXX      = g++\n"
      << "CXXFLAGS = -std=c++17 -Wall -Wextra -I.. -I../include -pthread\n\n"
      << "SRCS = main_generated.cpp ../team_manager.cpp ../dag.cpp\n\n"
      << "all: main_generated\n\n"
      << "main_generated: $(SRCS)\n"
      << "\t$(CXX) $(CXXFLAGS) -o $@ $(SRCS)\n\n"
      << "run: main_generated\n"
      << "\t./main_generated\n\n"
      << "clean:\n"
      << "\trm -f main_generated\n\n"
      << ".PHONY: all run clean\n";
}

// ---------------------------------------------------------------------------
//  Entry point
// ---------------------------------------------------------------------------

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0] << " <deployment_plan.json>\n";
        return 1;
    }
    const std::string plan_path = argv[1];

    std::vector<SubtaskGen>    subtasks;
    std::vector<ConnectionGen> conns;
    try {
        parse_plan(plan_path, subtasks, conns);
    } catch (const std::exception& e) {
        std::cerr << "Error parsing plan: " << e.what() << "\n";
        return 1;
    }

    // Build DAG from plan — reuses the same algorithms as the runtime
    DAG dag;
    for (const auto& s : subtasks)
        dag.add_node(s.id, nullptr);
    for (const auto& c : conns)
        dag.add_edge(c.upstream, c.downstream);

    std::vector<int> order;
    int              depth;
    try {
        order = dag.topological_sort();
        depth = dag.pipeline_depth();
    } catch (const std::exception& e) {
        std::cerr << "Error analysing DAG: " << e.what() << "\n";
        return 1;
    }

    std::cout << "Plan: " << plan_path << "\n"
              << "  subtasks: " << subtasks.size() << "\n"
              << "  connections: " << conns.size() << "\n"
              << "  pipeline_depth: " << depth << "\n\n";

    // Emit ring buffer sizes
    std::map<int, const SubtaskGen*> sub;
    for (const auto& s : subtasks) sub[s.id] = &s;

    std::cout << "Ring buffer sizes (N = max(2, ceil(D/T) + depth)):\n";
    for (const auto& c : conns) {
        const auto* up   = sub.at(c.upstream);
        const auto* down = sub.at(c.downstream);
        std::size_t n    = ring_buffer_n(up->period_ns, down->deadline_ns, depth);
        std::cout << "  edge " << c.upstream << "→" << c.downstream
                  << "  T=" << up->period_ns/1000000 << "ms"
                  << "  D=" << down->deadline_ns/1000000 << "ms"
                  << "  N=" << n << "\n";
    }
    std::cout << "\n";

    const std::string cpp_out  = "generated/main_generated.cpp";
    const std::string make_out = "generated/Makefile";

    try {
        generate_cpp(cpp_out, plan_path, subtasks, conns, order, dag, depth);
        generate_makefile(make_out);
    } catch (const std::exception& e) {
        std::cerr << "Error generating output: " << e.what() << "\n";
        return 1;
    }

    std::cout << "Generated:\n"
              << "  " << cpp_out  << "\n"
              << "  " << make_out << "\n\n"
              << "Build and run:\n"
              << "  cd generated && make run\n";
    return 0;
}
